kind: PersistentVolume
apiVersion: v1
metadata:
 name: mongo-pv
 labels:
  type: mongo-pv
spec:
 storageClassName: standard
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/mnt/mongo_data"
 nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node2
